# Generated by Django 3.1.4 on 2020-12-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('spitcoin', models.FloatField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('uid', models.CharField(blank=True, max_length=10, null=True)),
                ('branch', models.CharField(choices=[('COMP', 'COMP'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('MCA', 'MCA'), ('MTECH-CS', 'MTECH-CS'), ('MTECH-EXTC', 'MTECH-EXTC'), ('PHD-CS', 'PHD-CS'), ('PHD-EXTC', 'PHD-EXTC')], max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
