# Generated by Django 3.1.4 on 2020-12-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('spitcoin', models.FloatField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('year', models.IntegerField(default=1)),
                ('uid', models.CharField(max_length=10, null=True)),
                ('branch', models.CharField(choices=[('COMP', 'COMP'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('MCA', 'MCA')], max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1)),
                ('sub1', models.FloatField(null=True)),
                ('sub2', models.FloatField(null=True)),
                ('sub3', models.FloatField(null=True)),
                ('sub4', models.FloatField(null=True)),
                ('sub5', models.FloatField(null=True)),
                ('sub6', models.FloatField(null=True)),
                ('sub7', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=500, null=True)),
                ('about', models.TextField(null=True)),
                ('linkedin', models.CharField(max_length=50, null=True)),
                ('github', models.CharField(max_length=50, null=True)),
                ('resume_link', models.CharField(max_length=500, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='LostProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(null=True, upload_to='')),
                ('item', models.CharField(max_length=50, null=True)),
                ('desc', models.TextField(null=True)),
                ('claim', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(null=True)),
                ('happy', models.BooleanField(null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at1', models.FloatField(null=True)),
                ('at2', models.FloatField(null=True)),
                ('at3', models.FloatField(null=True)),
                ('at4', models.FloatField(null=True)),
                ('at5', models.FloatField(null=True)),
                ('at6', models.FloatField(null=True)),
                ('at7', models.FloatField(null=True)),
                ('cgpa1', models.FloatField(null=True)),
                ('cgpa2', models.FloatField(null=True)),
                ('cgpa3', models.FloatField(null=True)),
                ('cgpa4', models.FloatField(null=True)),
                ('cgpa', models.FloatField(null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
    ]
