# Generated by Django 3.1.4 on 2020-12-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20201206_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.CharField(choices=[('COMP', 'COMP'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('MCA', 'MCA'), ('MTECH-CS', 'MTECH-CS'), ('MTECH-EXTC', 'MTECH-EXTC'), ('PHD-CS', 'PHD-CS'), ('PHD-EXTC', 'PHD-EXTC')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('COMP', 'COMP'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('MCA', 'MCA'), ('MTECH-CS', 'MTECH-CS'), ('MTECH-EXTC', 'MTECH-EXTC'), ('PHD-CS', 'PHD-CS'), ('PHD-EXTC', 'PHD-EXTC')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub1',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub2',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub3',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub4',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub5',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub6',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub7',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(),
        ),
    ]
