# Generated by Django 3.1.4 on 2020-12-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20201206_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='at1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='at2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='at3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='at4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='at5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='at6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='at7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='cgpa1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='cgpa2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='cgpa3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='cgpa4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.CharField(choices=[('COMP', 'COMP'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('MCA', 'MCA'), ('MTECH-CS', 'MTECH-CS'), ('MTECH-EXTC', 'MTECH-EXTC'), ('PHD-CS', 'PHD-CS'), ('PHD-EXTC', 'PHD-EXTC')], default='MCA', max_length=10, null=True),
        ),
    ]
