# Generated by Django 3.1.4 on 2020-12-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20201206_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub1',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub2',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub3',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub4',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub5',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub6',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub7',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
