# Generated by Django 3.1.3 on 2020-12-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20201206_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='github',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='linkedin',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='resume_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
