# Generated by Django 3.1.4 on 2020-12-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20201207_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
