# Generated by Django 3.1.4 on 2020-12-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_auto_20201206_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_manager',
            field=models.BooleanField(default=True),
        ),
    ]
