# Generated by Django 3.1.3 on 2020-12-06 12:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=100)),
                ('icon', models.ImageField(null=True, upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, max_length=50, null=True)),
                ('instagram', models.URLField(blank=True, max_length=50, null=True)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(max_length=100)),
                ('dop', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.FloatField(default=0)),
                ('regLink', models.URLField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='committee.committee')),
            ],
        ),
    ]
