# Generated by Django 3.1.4 on 2020-12-06 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committee', '0002_auto_20201206_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='is_committee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee', to=settings.AUTH_USER_MODEL),
        ),
    ]
