# Generated by Django 3.1.4 on 2020-12-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20201207_0206'),
        ('committee', '0004_events_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='paid',
            field=models.ManyToManyField(to='student.Student'),
        ),
    ]
