# Generated by Django 3.1.4 on 2020-12-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20201207_0206'),
        ('committee', '0005_events_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='paid',
            field=models.ManyToManyField(blank=True, null=True, to='student.Student'),
        ),
    ]
